"""Initial migration: students, diary_entries, marks

Revision ID: 08e781556b0e
Revises: 
Create Date: 2025-12-01 22:55:24.285352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e781556b0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('classwork', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attendance', sa.Text(), nullable=True),
    sa.Column('share_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("attendance IN ('Present', 'Absent')", name='check_attendance'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_key'),
    sa.UniqueConstraint('student_id', 'entry_date', name='uq_student_entry_date')
    )
    op.create_table('marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('max_mark', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('share_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('diary_entries')
    op.drop_table('students')
    # ### end Alembic commands ###
